// <auto-generated />
namespace AskAway.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MarkingofQuestionsandAnswers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MarkingofQuestionsandAnswers));
        
        string IMigrationMetadata.Id
        {
            get { return "202202021220176_Marking-of-Questions-and-Answers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
